default_context:
  project_name: 'podium'
  project_slug: 'podium'
  domain_main: 'getpodium.fm'
  domain_staging: 'stag.getpodium.fm'
  docker_swarm_stack_name_main: 'getpodium-fm'
  docker_swarm_stack_name_staging: 'stag-getpodium-fm'
  secret_key: 'dc1016b4f6a1605d02d38d6238c876e0614ca41237f6fa06b3644ef0930b35c7'
  first_superuser: 'admin@getpodium.fm'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.getpodium.fm", "https://stag.getpodium.fm", "https://getpodium.fm", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@getpodium.fm'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin@getpodium.fm'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'getpodium.fm'
  traefik_constraint_tag_staging: 'stag.getpodium.fm'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
